/**
 * Wetr.WebService
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GroupedResultRecord { 
    dateTimeStart?: Date;
    periodType?: GroupedResultRecord.PeriodTypeEnum;
    measurementTypeID?: number;
    deviceID?: number;
    unitOfMeasureID?: number;
    value?: number;
}
export namespace GroupedResultRecord {
    export type PeriodTypeEnum = 0 | 1 | 2 | 3 | 4;
    export const PeriodTypeEnum = {
        NUMBER_0: 0 as PeriodTypeEnum,
        NUMBER_1: 1 as PeriodTypeEnum,
        NUMBER_2: 2 as PeriodTypeEnum,
        NUMBER_3: 3 as PeriodTypeEnum,
        NUMBER_4: 4 as PeriodTypeEnum
    };
}
