/**
 * Wetr.WebService
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MeasurementDevice } from './measurementDevice';
import { MeasurementType } from './measurementType';


export interface MeasurementFilter { 
    aggregationType?: MeasurementFilter.AggregationTypeEnum;
    periodType?: MeasurementFilter.PeriodTypeEnum;
    measurementDevice?: MeasurementDevice;
    measurementType?: MeasurementType;
    dateFrom?: Date;
    dateTo?: Date;
    radiusKm?: number;
}
export namespace MeasurementFilter {
    export type AggregationTypeEnum = 0 | 1 | 2 | 3 | 4;
    export const AggregationTypeEnum = {
        NUMBER_0: 0 as AggregationTypeEnum,
        NUMBER_1: 1 as AggregationTypeEnum,
        NUMBER_2: 2 as AggregationTypeEnum,
        NUMBER_3: 3 as AggregationTypeEnum,
        NUMBER_4: 4 as AggregationTypeEnum
    };
    export type PeriodTypeEnum = 0 | 1 | 2 | 3 | 4;
    export const PeriodTypeEnum = {
        NUMBER_0: 0 as PeriodTypeEnum,
        NUMBER_1: 1 as PeriodTypeEnum,
        NUMBER_2: 2 as PeriodTypeEnum,
        NUMBER_3: 3 as PeriodTypeEnum,
        NUMBER_4: 4 as PeriodTypeEnum
    };
}
