// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Wetr.Simulator.REST
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Measurements.
    /// </summary>
    public static partial class MeasurementsExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='measurement'>
            /// </param>
            public static void InsertMeasurement(this IMeasurements operations, Measurement measurement)
            {
                Task.Factory.StartNew(s => ((IMeasurements)s).InsertMeasurementAsync(measurement), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='measurement'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task InsertMeasurementAsync(this IMeasurements operations, Measurement measurement, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.InsertMeasurementWithHttpMessagesAsync(measurement, null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='measurements'>
            /// </param>
            public static void InsertMultipleMeasurements(this IMeasurements operations, IList<Measurement> measurements)
            {
                Task.Factory.StartNew(s => ((IMeasurements)s).InsertMultipleMeasurementsAsync(measurements), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='measurements'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task InsertMultipleMeasurementsAsync(this IMeasurements operations, IList<Measurement> measurements, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.InsertMultipleMeasurementsWithHttpMessagesAsync(measurements, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
