// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Wetr.Simulator.REST.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Community
    {
        /// <summary>
        /// Initializes a new instance of the Community class.
        /// </summary>
        public Community() { }

        /// <summary>
        /// Initializes a new instance of the Community class.
        /// </summary>
        public Community(int? id = default(int?), int? postalCode = default(int?), string name = default(string), int? districtID = default(int?))
        {
            ID = id;
            PostalCode = postalCode;
            Name = name;
            DistrictID = districtID;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public int? PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DistrictID")]
        public int? DistrictID { get; set; }

    }
}
