// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Wetr.Simulator.REST.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MeasurementDevice
    {
        /// <summary>
        /// Initializes a new instance of the MeasurementDevice class.
        /// </summary>
        public MeasurementDevice() { }

        /// <summary>
        /// Initializes a new instance of the MeasurementDevice class.
        /// </summary>
        public MeasurementDevice(int? id = default(int?), int? communityID = default(int?), string deviceName = default(string), string address = default(string), double? longitude = default(double?), double? latitude = default(double?))
        {
            ID = id;
            CommunityID = communityID;
            DeviceName = deviceName;
            Address = address;
            Longitude = longitude;
            Latitude = latitude;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CommunityID")]
        public int? CommunityID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeviceName")]
        public string DeviceName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Longitude")]
        public double? Longitude { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Latitude")]
        public double? Latitude { get; set; }

    }
}
