// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Wetr.Simulator.REST.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class MeasurementType
    {
        /// <summary>
        /// Initializes a new instance of the MeasurementType class.
        /// </summary>
        public MeasurementType() { }

        /// <summary>
        /// Initializes a new instance of the MeasurementType class.
        /// </summary>
        public MeasurementType(int? id = default(int?), string description = default(string))
        {
            ID = id;
            Description = description;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
