// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Wetr.Simulator.REST.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Measurement
    {
        /// <summary>
        /// Initializes a new instance of the Measurement class.
        /// </summary>
        public Measurement() { }

        /// <summary>
        /// Initializes a new instance of the Measurement class.
        /// </summary>
        public Measurement(int? id = default(int?), int? typeID = default(int?), int? deviceID = default(int?), double? value = default(double?), int? unitOfMeasureID = default(int?), DateTime? timestamp = default(DateTime?))
        {
            ID = id;
            TypeID = typeID;
            DeviceID = deviceID;
            Value = value;
            UnitOfMeasureID = unitOfMeasureID;
            Timestamp = timestamp;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TypeID")]
        public int? TypeID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DeviceID")]
        public int? DeviceID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public double? Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitOfMeasureID")]
        public int? UnitOfMeasureID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Timestamp")]
        public DateTime? Timestamp { get; set; }

    }
}
